user: www-data
group: www-data
address: proxy.gives.co
port: 443
pid: tmp/pids/thin.pid
wait: 30
timeout: 30
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 3
daemonize: true
socket: /tmp/thin.sock
ssl: true
ssl_key_file: /etc/letsencrypt/live/proxy.gives.co/privkey.pem
ssl_cert_file: /etc/letsencrypt/live/proxy.gives.co/fullchain.pem
ssl_disable_verify: false
