port: 3002
pid: tmp/pids/thin.pid
wait: 30
timeout: 30
log: log/thin.log
max_conns: 1024
require: []
environment: staging
max_persistent_conns: 512
servers: 3
threaded: true
no-epoll: true
daemonize: true
socket: tmp/sockets/thin.sock
tag: reverse-proxy
